model_tag: mambaout_base_plus_rw.sw_e150_in12k_ft_in1k
backbone: mambaout_base_plus_rw.sw_e150_in12k_ft_in1k
batch_size: 8
epochs: 12
learning_rate: 0.00001
patience: 6
input_shape: [1, 32, 32]
global_max: 121.79151153564453
output_dir: training_output/
dataset_subdir: jet_ml_benchmark_config_01_to_09_alpha_0.2_0.3_0.4_q0_1.5_2.0_2.5_MMAT_MLBT_size_1000_balanced_unshuffled
group_size: 1